# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2


# Personal info
name: yera choi
title: A new Back-end Web Developer
email: qeen0013@naver.com
website: https://github.com/choiyera

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: choiyera
  
content:
  - title: Myongji College # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Myongji College
        quote: >
          Myongji College 소프트웨어콘텐츠학과 졸업
        description: | # this will include new lines to allow paragraphs
                                                               전공<br />
                                                               
                                          웹프로그래밍(2018-1학기)         프로그래밍기초(2018-1학기) <br />
                                          앱프로그래밍(2018-1학기)         게임개발기초(2018-1학기) <br />
                                          서버프로그래밍기초(2018-2학기)    앱개발기초(2018-2학기) <br />
                                          네트워크게임(2018-2학기)         게임개발응용(2018-2학기) <br />
                                          앱개발응용(2019-1학기)           게임인공지능(2019-1학기) <br />
                                          가상현실게임(2019-1학기)         콘텐츠기획(2019-1학기) <br />
                                          게임개발실무(2019-2학기)         앱개발실무(2019-2학기) <br />
                                          가상현실그래픽실습(2019-2학기)
  - title: 국비과정 교육 수료 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 전자정부 표준 프레임워크 응용SW개발자양성
        quote: >
          더 많은 것을 배워보고싶고, 여러 경험과 다른 사람과의 프로젝트를 함께 해보고 싶어 국비과정을 수료하게되었습니다.
        description: | # this will include new lines to allow paragraphs
                            국비과정을 통해 개발자로써 필요한 부분을 배워 발전할 수 있는 계기가 되었고,
          
                            여러사람들과의 프로젝트를 통해 한층 더 개발자라는 직업에 매력을 느끼게 되었습니다.
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 일개미
        link: https://github.com/choiyera/ilgaemiproject.git
        # link_text: Project Website
        additional_links:
          - title: 프로젝트 및 시연 ppt
            icon: fab fa-github
            url: http://naver.me/Fl2egb6I
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          팀프로젝트에서 만들었던 프로젝트입니다. 링크를 통해 프로젝트 소스코드를 확인하실 수 있습니다.
          아이콘을 클릭시 프로젝트 시연 ppt를 확인하실 수 있습니다.
        description: | # this will include new lines to allow paragraphs
          프로젝트를 진행하면서 여러사람과의 협업 즉 <mark>팀워크</mark>가 얼마나 중요한지 느껴보는 시간이었습니다.
          
          팀원이 부족한 부분은 제가 채워나가고 제가 부족한 부분은 팀원이 채워나가며 프로젝트를 완성했을 때 얼마나 <mark>값진 경험</mark>인지 느끼고 발전하는 시간이었습니다.
  - title: 입사지원서 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 입사지원서
        link: http://naver.me/55R6sbwP
        # link_text: 입사지원서
        quote: >
          신입 개발자로써 성실함과 꾸준함 얼마나 배우고자하여 성장하는지 중요하다고 생각합니다. 사회에 나온지 긴 시간은 아니지만 그 시간동안 꾸준히 목표를 향해 달려왔습니다.
        description: | # this will include new lines to allow paragraphs
                   국비 과정에서 JAVA, JSP, SPRING, HTML, CSS 등을 공부하였고, 팀원들과 함께 프로젝트를 진행한 바 있습니다.
          
                   프로젝트에서 맡았던 역할 등은 <mark>ppt</mark>를 참고해주시기 바랍니다.
                                 
  - title: 구현가능한 기능 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구현가능한 기능
        quote: >
        description: | # this will include new lines to allow paragraphs
         - 회원관련(로그인, 회원가입, 삭제, 변경 등) CRUD
         - Session 을 이용한 로그인 처리 및 정보 사용(아이디 기억하기, 세션을 활용한 로그인 정보 넘겨서 다른 부분에서 처리)
         - JSTL을 이용한 기능 구축
         - ArrayList, Map을 통한 데이터 처리
         - 게시판 CRUD 구현
         - 데이터베이스 xml을 이용하여 검색, 삽입, 변경, 삭제 가능
         - ORACLE을 이용한 데이터베이스 설계 및 구현
         - html, css 활용가능, js를 통한 유효성 검사
         - SQL Developer, DBeaver, Oracle 사용 데이터베이스 관리
# Footer
footer_show_references: true
# references_title: Nice to meet you (Override references text)
 
# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
